name: Validate PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]  # Only trigger when a PR is created

jobs:
  echo-pr-details:
    runs-on: ubuntu-latest

    steps:
      - name: Echo PR Info
        run: |
          echo "Pull Request created!"
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.actor }}"
          echo "Source branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target branch: ${{ github.event.pull_request.base.ref }}"
          
          echo "Checking checklist completion..."

          PR_BODY="${{ github.event.pull_request.body }}"
          echo "PR Body:"
          echo "$PR_BODY"

          echo "------ Matched Checklist Lines ------"
          echo "$PR_BODY" | grep -n '\[.*\]' || echo "✅ No checklist items found"
          echo "------------------------------------"

          # Safely count exact unchecked checkboxes using awk
          UNCHECKED_COUNT=$(echo "$PR_BODY" | awk '
            /^\s*-\s*\[\s*\]\s*/ { count++ }
            END { print count+0 }
          ')

          echo "Unchecked count: $UNCHECKED_COUNT"

          if [ "$UNCHECKED_COUNT" -eq 0 ]; then
            echo "✅ All checklist items are completed."
          else
            echo "❌ Incomplete checklist detected."
            exit 1
          fi
